### ISSUE TITLE
make api more user-friendly

### ISSUE THREAD

**Issue by wisealex2** [KonanM/static_enum#1]
Thanks for the library - nice idea and implementation

a small note -api will be cleaner if it is implemented boost way
in the main header file only declarations of your public api
in the detail folder an implementation header file with detail namespace and definitions of the public api functions
the main header will include implementation header (probably with a guard)

**Comment by KonanM** [comment]
I generally agree that the file would be a bit cleaner when I put the detail part into it's own file. That being said the con is clearly the ease of distribution. I would actually have to consider amalgate and do it it like json for modern C++. Provide both a multi header project and a single header file.
I think it's currently not worth the hassle, as this library literally provides 4 functions and is less than 150 LOC.
